---
title: "Bowtie, Bowtie 2 and HISAT scaling results"
output: html_notebook
---

```{r}
# setwd('~/git/bowtie-scaling/thread_scaling/scripts')
stampede_knl_fn <- 'stampede_knl/stampede_knl_results_20180128.csv'
stampede_skx_fn <- 'stampede_skx/stampede_skx_iot_results_20180608.csv'
marcc_bigmem_fn <- 'marcc_lbm/marcc_lbm_results_20180127.csv'
MAX_SECS <- 1000
```

```{r libraries}
library(ggplot2)
library(plyr)
library(dplyr)
library(grid)
library(gridExtra)
library(tables)
library(RColorBrewer)
```

```{r set_dir}
# Depends on your system
if(grepl('ben-mbp', Sys.info()[['nodename']])) {
    setwd('~/git/bowtie-scaling/thread_scaling/scripts')
} else {
}
```

```{r plot_util}
# Borrowed from: https://rpubs.com/sjackman/grid_arrange_shared_legend
# Thanks to Shaun Jackman
grid_arrange_shared_legend <- function(...) {
    plots <- list(...)
    g <- ggplotGrob(plots[[2]] + theme(legend.position="bottom"))$grobs
    legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
    lheight <- sum(legend$height)
    grid.arrange(
        do.call(arrangeGrob, lapply(plots, function(x)
            x + theme(legend.position="none"))),
        legend,
        ncol = 1,
        heights = unit.c(unit(1, "npc") - lheight, lheight))
}

grid_arrange_shared_legend2 <- function(show_legend, num_rows, legend_plot_id, ...) {
    plots <- list(...)
    if (show_legend) {
      g <- ggplotGrob(plots[[legend_plot_id]] + theme(legend.position="bottom"))$grobs
      legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
      lheight <- sum(legend$height)
      plots_arg <- lapply(plots, function(x)  x + theme(legend.position="none"))
      plots_arg$nrow <- num_rows
      grid.arrange(
          do.call(arrangeGrob, plots_arg),
          legend,
          ncol = 1,
          heights = unit.c(unit(1, "npc") - lheight, lheight))
    }
    else {
      g <- ggplotGrob(plots[[legend_plot_id]] + theme(legend.position="bottom"))$grobs
      legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
      grid.arrange(
          do.call(arrangeGrob, lapply(plots, function(x)
              x + theme(legend.position="none"))),
          ncol = 1,
          heights = unit.c(unit(1, "npc")))
    }
}
```

```{r summarize_col_func}
summarize_col <- function(df, colname) {
  mean_str <- paste(colname, 'mean', sep='_')
  min_str <- paste(colname, 'min', sep='_')
  max_str <- paste(colname, 'max', sep='_')
  df[[mean_str]] <- 0
  df[[min_str]] <- 0
  df[[max_str]] <- 0
  for(i in 1:nrow(df)) {
    rw <- df[[colname]][i]
    vec <- as.numeric(unlist(strsplit(rw, ' ')))
    df[[mean_str]][i] <- mean(vec)
    df[[min_str]][i] <- min(vec)
    df[[max_str]][i] <- max(vec)
  }
  return(df)
}
```

```{r read_table_helpers}
add_reads <- function(m) {
  m$reads_per_thread <- unlist(sapply(paste(m$aligner, m$pe, m$machine), switch,
                    'bt unp KNL'=450000,
                    'bt2 unp KNL'=65000,
                    'bwa unp KNL'=65000,
                    'ht unp KNL'=400000,
                    'bt pe KNL'=37500,
                    'bt2 pe KNL'=16000,
                    'bwa pe KNL'=16000,
                    'ht pe KNL'=250000,
                    'bt unp Broadwell'=1000000,
                    'bt2 unp Broadwell'=200000,
                    'bwa unp Broadwell'=200000,
                    'ht unp Broadwell'=1200000,
                    'bt pe Broadwell'=110000,
                    'bt2 pe Broadwell'=85000,
                    'bwa pe Broadwell'=85000,
                    'ht pe Broadwell'=550000,
                    'bt unp Skylake'=1000000,
                    'bt2 unp Skylake'=200000,
                    'bwa unp Skylake'=200000,
                    'ht unp Skylake'=1200000,
                    'bt pe Skylake'=110000,
                    'bt2 pe Skylake'=85000,
                    'bwa pe Skylake'=85000,
                    'ht pe Skylake'=550000
                    ))
  m
}

parse_results <- function(fn, machine) {
  m <- read.table(fn, sep=',', comment.char='', quote='', header=T, stringsAsFactors=F)
  m <- summarize_col(m, 'thread_times')
  m <- summarize_col(m, 'cpu_changeovers')
  m <- summarize_col(m, 'node_changeovers')
  m$series <- ifelse(m$series == '', 'bwa', m$series)
  m <- m[!is.na(m$series),]
  m$machine <- machine
  m <- add_reads(m)
  bases_40x <- 3e9 * 40
  read_len <- 100
  m <- m %>% dplyr::group_by(series, pe, attempt, totthreads, reads_per_thread, aligner) %>%
    dplyr::summarise(thread_times_max=max(thread_times_max),
              thread_times_min=min(thread_times_min),
              thread_times_mean=mean(thread_times_mean),
              threads_div_max=(totthreads[1] * reads_per_thread[1]) / thread_times_max,
              tot_secs_40x_unp=(bases_40x/read_len)/threads_div_max,
              tot_secs_40x_pe=(bases_40x/(read_len*2))/threads_div_max)
  m <- m[m$thread_times_max < MAX_SECS,]
  m$machine <- machine
  m
}
```

```{r read_table}
m <- rbind(parse_results(stampede_knl_fn, 'KNL'),
           parse_results(stampede_skx_fn, 'Skylake'),
           parse_results(marcc_bigmem_fn, 'Broadwell'))
m$series <- factor(m$series)
m$aligner[m$aligner == 'bwa'] <- 'bt2'
m_bm <- m[m$machine == 'Broadwell',]
m_sk <- m[m$machine == 'Skylake',]
m_st <- m[m$machine == 'KNL',]
```

```{r scaling_plot_func}
scaling_plot_filter <- function(m, want_aligner, want_pe) {
  m %>% filter(attempt == 1 & aligner %in% want_aligner & ((pe == 'pe') == want_pe))
}

scaling_plot <- function(m, want_aligner, want_pe, label_x=F, label_y=F, label_main=NA, ncolors=6, alpha=0.5, color_set="Set1") {
  m <- scaling_plot_filter(m, want_aligner, want_pe)
  mg <- m %>% dplyr::group_by(series, pe, attempt, aligner) %>%
    dplyr::summarise(threads_div_max_max=thread_times_max[which(threads_div_max == max(threads_div_max))[1]],
              threads_div_max_threads=totthreads[which(threads_div_max == max(threads_div_max))[1]])
  ggplot() + 
    geom_line(data=m, position=position_dodge(width=0.2), aes(x=totthreads, y=thread_times_max, color=series)) +
    geom_point(data=mg, aes(x=threads_div_max_threads, y=threads_div_max_max, fill=series), shape=22, color='black', size=3, alpha=alpha) +
    expand_limits(x=0, y=0) +
    labs(x=if(label_x) {'# threads'} else {''},
         y=if(label_y) {'Thread time'} else {''},
         title=if(is.na(label_main)) {''} else {label_main}) +
    scale_fill_manual(values = brewer.pal(ncolors, color_set)) +
    scale_colour_manual(values = brewer.pal(ncolors, color_set)) +
    theme_bw() +
    theme(legend.title=element_blank(), legend.key.width=unit(2, "line"))
}
```

```{r adjust_series}
adjust_series <- function(m, short, long) {
  m <- data.frame(m)
  m <- m %>% filter(series %in% short & attempt == 1)
  reord <- rep(0, nrow(m))
  for(i in 1:length(short)) {
    reord[m$series == short[i]] <- i
  }
  m$series <- plyr::mapvalues(reorder(m$series, reord), from=short, to=long)
  m
}
```

```{r three_by_three}
three_by_three <- function(m_sk_base, m_bm_base, m_st_base, want_pe) {
    grid_arrange_shared_legend(
        scaling_plot(m_sk_base, c('bt'), want_pe, label_x=F, label_y=T, label_main='Skylake Bowtie'),
        scaling_plot(m_sk_base, c('bt2'), want_pe, label_x=F, label_y=F, label_main='Skylake Bowtie 2'),
        scaling_plot(m_sk_base, c('ht'), want_pe, label_x=F, label_y=F, label_main='Skylake HISAT'),
        scaling_plot(m_bm_base, c('bt'), want_pe, label_x=F, label_y=T, label_main='Broadwell Bowtie'),
        scaling_plot(m_bm_base, c('bt2'), want_pe, label_x=F, label_y=F, label_main='Broadwell Bowtie 2'),
        scaling_plot(m_bm_base, c('ht'), want_pe, label_x=F, label_y=F, label_main='Broadwell HISAT'),
        scaling_plot(m_st_base, c('bt'), want_pe, label_x=T, label_y=T, label_main='KNL Bowtie'),
        scaling_plot(m_st_base, c('bt2'), want_pe, label_x=T, label_y=F, label_main='KNL Bowtie 2'),
        scaling_plot(m_st_base, c('ht'), want_pe, label_x=T, label_y=F, label_main='KNL HISAT'))
}
```

```{r single_machine}
single_machine <- function(m, color_set='YlOrRd') {
    grid_arrange_shared_legend(
        scaling_plot(m, c('bt'),  F, label_x=F, label_y=F, label_main='Bowtie unpaired',   ncolors=7, alpha=1.0, color_set=color_set),
        scaling_plot(m, c('bt'),  T, label_x=F, label_y=F, label_main='Bowtie paired',     ncolors=7, alpha=1.0, color_set=color_set),
        scaling_plot(m, c('bt2'), F, label_x=F, label_y=F, label_main='Bowtie 2 unpaired', ncolors=7, alpha=1.0, color_set=color_set),
        scaling_plot(m, c('bt2'), T, label_x=F, label_y=F, label_main='Bowtie 2 paired',   ncolors=7, alpha=1.0, color_set=color_set),
        scaling_plot(m, c('ht'),  F, label_x=T, label_y=F, label_main='HISAT unpaired',    ncolors=7, alpha=1.0, color_set=color_set),
        scaling_plot(m, c('ht'),  T, label_x=T, label_y=F, label_main='HISAT paired',      ncolors=7, alpha=1.0, color_set=color_set))
}
```

```{r baseline_plots_all}
baseline_short <- c('baseline-old',
                    'baseline-tbbspin',
                    'baseline-tbbstd',
                    'baseline-tbbq',
                    'final-mp16')
baseline_long  <- c('TinyThread++ spin  ',
                    'TBB spin  ',
                    'TBB standard  ',
                    'TBB queueing  ',
                    'MP baseline')

baseline_plots_all <- function(m_st, m_sk, m_bm, want_pe) {
  m_sk_base <- adjust_series(m_sk, baseline_short, baseline_long)
  m_bm_base <- adjust_series(m_bm, baseline_short, baseline_long)
  m_st_base <- adjust_series(m_st, baseline_short, baseline_long)
  three_by_three(m_sk_base, m_bm_base, m_st_base, want_pe)
}
```

```{r baseline_plots_all_unp}
baseline_plots_all(m_st, m_sk, m_bm, F)

pdf(file='baseline_unp.pdf', onefile=F)
baseline_plots_all(m_st, m_sk, m_bm, F)
dev.off()

pdf(file='baseline_unp_wide.pdf', onefile=F, width=10, height=6)
baseline_plots_all(m_st, m_sk, m_bm, F)
dev.off()
```


```{r baseline_plots_all_pe}
baseline_plots_all(m_st, m_sk, m_bm, T)

pdf(file='baseline_pe.pdf', onefile=F)
baseline_plots_all(m_st, m_sk, m_bm, T)
dev.off()

pdf(file='baseline_pe_wide.pdf', onefile=F, width=10, height=6)
baseline_plots_all(m_st, m_sk, m_bm, T)
dev.off()

```

```{r parsing_plots_all}
parsing_short <- c('baseline-tbbq',
                   'parsing-clean',
                   'parsing-batch',
                   'final-mp16')
parsing_long  <- c('Original (O)  ',
                   'Deferred (D)  ',
                   'Batch deferred (B)  ',
                   'MP baseline')

parsing_plots_all <- function(m_st, m_sk, m_bm, want_pe) {
  m_sk_base <- adjust_series(m_sk, parsing_short, parsing_long)
  m_bm_base <- adjust_series(m_bm, parsing_short, parsing_long)
  m_st_base <- adjust_series(m_st, parsing_short, parsing_long)
  three_by_three(m_sk_base, m_bm_base, m_st_base, want_pe)
}
```

```{r parsing_plots_all_unp}
parsing_plots_all(m_st, m_sk, m_bm, F)

pdf(file='parsing_unp.pdf', onefile=F)
parsing_plots_all(m_st, m_sk, m_bm, F)
dev.off()

pdf(file='parsing_unp_wide.pdf', onefile=F, width=10, height=6)
parsing_plots_all(m_st, m_sk, m_bm, F)
dev.off()

```

```{r parsing_plots_all_pe}
parsing_plots_all(m_st, m_sk, m_bm, T)

pdf(file='parsing_pe.pdf', onefile=F)
parsing_plots_all(m_st, m_sk, m_bm, T)
dev.off()

pdf(file='parsing_pe_wide.pdf', onefile=F, width=10, height=6)
parsing_plots_all(m_st, m_sk, m_bm, T)
dev.off()
```

```{r final_plots_all}
final_short = c('parsing-batch',
                'final-block',
                'final-block-multi16',
                'final-mp16',
                'bwa')
final_long = c('Batch (B)  ',
               'Block (L), 1 output  ',
               'Block (L), 16 outputs  ',
               'MP baseline  ',
               'BWA-MEM')

stopifnot(sum(m_st$series == 'bwa') > 0)
stopifnot(sum(m_st$aligner == 'bwa') == 0)

final_plots_all <- function(m_st, m_sk, m_bm, want_pe) {
  m_sk_base <- adjust_series(m_sk, final_short, final_long)
  m_bm_base <- adjust_series(m_bm, final_short, final_long)
  m_st_base <- adjust_series(m_st, final_short, final_long)
  three_by_three(m_sk_base, m_bm_base, m_st_base, want_pe)
}
```

```{r final_plots_all_unp}
final_plots_all(m_st, m_sk, m_bm, F)

pdf(file='final_unp.pdf', onefile=F)
final_plots_all(m_st, m_sk, m_bm, F)
dev.off()

pdf(file='final_unp_wide.pdf', onefile=F, width=10, height=6)
final_plots_all(m_st, m_sk, m_bm, F)
dev.off()
```

```{r final_plots_all_pe}
final_plots_all(m_st, m_sk, m_bm, T)

pdf(file='final_pe.pdf', onefile=F)
final_plots_all(m_st, m_sk, m_bm, T)
dev.off()

pdf(file='final_pe_wide.pdf', onefile=F, width=10, height=6)
final_plots_all(m_st, m_sk, m_bm, T)
dev.off()
```

```{r iot_plots_all}
iot_short = c('parsing-batch',
              'parsing-batch-iot',
              'final-block',
              'final-block-multi16',
              'final-mp16')
iot_long = c('Batch (B)  ',
             'Batch, I/O threads (B*)  ',
             'Block (L), 1 output  ',
             'Block (L), 16 outputs  ',
             'MP baseline')

iot_plot <- function(m_sk) {
  m_sk_base <- adjust_series(m_sk, iot_short, iot_long)
  scaling_plot(m_sk_base, c('bt'), F, label_x=T, label_y=T,
      label_main='Skylake Bowtie')
}

iot_plot(m_sk)

pdf(file='iot_unp.pdf', onefile=F)
iot_plot(m_sk)
dev.off()
```

```{r num_outputs}
nout_short = c('final-block',
               'final-block-multi2',
               'final-block-multi4',
               'final-block-multi8',
               'final-block-multi16',
               'final-mp16')
nout_long = c('1 output',
              '2 outputs',
              '4 outputs',
              '8 outputs',
              '16 outputs',
              'MP baseline')

num_outputs_plots_all <- function(m_st, m_sk, m_bm, want_pe) {
  m_sk_base <- adjust_series(m_sk, nout_short, nout_long)
  m_bm_base <- adjust_series(m_bm, nout_short, nout_long)
  m_st_base <- adjust_series(m_st, nout_short, nout_long)
  three_by_three(m_sk_base, m_bm_base, m_st_base, want_pe)
}
```

```{r num_outputs_plots_all_unp}
num_outputs_plots_all(m_st, m_sk, m_bm, F)

pdf(file='nout_unp.pdf', onefile=F)
num_outputs_plots_all(m_st, m_sk, m_bm, F)
dev.off()

pdf(file='nout_unp_wide.pdf', onefile=F, width=10, height=6)
num_outputs_plots_all(m_st, m_sk, m_bm, F)
dev.off()
```

```{r num_outputs_plots_all_pe}
num_outputs_plots_all(m_st, m_sk, m_bm, T)

pdf(file='nout_pe.pdf', onefile=F)
num_outputs_plots_all(m_st, m_sk, m_bm, T)
dev.off()

pdf(file='nout_pe_wide.pdf', onefile=F, width=10, height=6)
num_outputs_plots_all(m_st, m_sk, m_bm, T)
dev.off()
```

```{r batch_size_plots}
batch_short = c('parsing-batch8',
               'parsing-batch16',
               'parsing-batch',
               'parsing-batch48',
               'parsing-batch64',
               'parsing-batch128',
               'parsing-batch256')
batch_long = c('8',
              '16',
              '32',
              '48',
              '64',
              '128',
              '256')

batch_plots_all <- function(m) {
  single_machine(adjust_series(m, batch_short, batch_long))
}
```

```{r batch_plots_all_unp}
batch_plots_all(m_st)

pdf(file='batch_sz.pdf', onefile=F)
batch_plots_all(m_st)
dev.off()

pdf(file='batch_sz_wide.pdf', onefile=F, width=10, height=6)
batch_plots_all(m_st)
dev.off()
```

```{r lustre_plots}
lustre_adjust_series <- function(m) {
  m <- data.frame(m)
  m$lustre <- grepl('^.*-lustre$', m$series)
  m$series[m$series == 'parsing-batch-lustre'] <- 'parsing-batch'
  m$series[m$series == 'final-block-lustre'] <- 'final-block'
  m$series[m$series == 'final-mp16-lustre'] <- 'final-mp16'
  m$series <- factor(m$series)
  reord <- rep(0, nrow(m))
  reord[m$series == 'parsing-batch'] <- 1
  reord[m$series == 'final-block'] <- 2
  reord[m$series == 'final-mp16'] <- 3
  m$series <- reorder(m$series, reord)
  m$series <- plyr::mapvalues(m$series,
                              from = c('parsing-batch',
                                       'final-block',
                                       'final-mp16'),
                              to = c('B-parsing',
                                     'L-parsing',
                                     'MP baseline'))
  m
}

lustre_plot <- function(m, want_aligner, want_pe, label_x=F, label_y=F, label_main=NA, ncolors=5, alpha=0.5, color_set="Set1") {
  m <- scaling_plot_filter(m, want_aligner, want_pe)
  mg <- m %>% dplyr::group_by(series, pe, attempt, aligner) %>%
    dplyr::summarise(threads_div_max_max=thread_times_max[which(threads_div_max == max(threads_div_max))[1]],
              threads_div_max_threads=totthreads[which(threads_div_max == max(threads_div_max))[1]])
  ggplot() + 
    geom_line(data=m, position=position_dodge(width=0.2), aes(x=totthreads, y=thread_times_max, color=series, linetype=lustre)) +
    geom_point(data=mg, aes(x=threads_div_max_threads, y=threads_div_max_max, fill=series), shape=22, color='black', size=3, alpha=alpha) +
    expand_limits(x=0, y=0) +
    labs(x=if(label_x) {'# threads'} else {''},
         y=if(label_y) {'Thread time'} else {''},
         title=if(is.na(label_main)) {''} else {label_main}) +
    scale_fill_manual(values = brewer.pal(ncolors, color_set)) +
    scale_colour_manual(values = brewer.pal(ncolors, color_set)) +
    theme_bw() +
    theme(legend.title=element_blank(), legend.key.width=unit(2, "line"))
}

lustre_plots_all <- function(m_st) {
  m_st_base <- m_st[grepl('^parsing-batch(-lustre)?$', m_st$series) |
                    grepl('^final-block(-lustre)?$', m_st$series) |
                    grepl('^final-mp16(-lustre)?$', m_st$series),] %>% filter(attempt == 1)
  m_st_base <- lustre_adjust_series(m_st_base)
  grid_arrange_shared_legend(
      lustre_plot(m_st_base, c('bt'), F, label_x=F, label_y=F, label_main='KNL Bowtie unpaired'),
      lustre_plot(m_st_base, c('bt'), T, label_x=F, label_y=F, label_main='KNL Bowtie paired'),
      lustre_plot(m_st_base, c('bt2'), F, label_x=F, label_y=F, label_main='KNL Bowtie 2 unpaired'),
      lustre_plot(m_st_base, c('bt2'), T, label_x=F, label_y=F, label_main='KNL Bowtie 2 paired'),
      lustre_plot(m_st_base, c('ht'), F, label_x=T, label_y=F, label_main='KNL HISAT unpaired'),
      lustre_plot(m_st_base, c('ht'), T, label_x=T, label_y=F, label_main='KNL HISAT paired'))
}
```

```{r lustre_plots_all}
lustre_plots_all(m_st)
pdf(file='lustre.pdf', onefile=F)
lustre_plots_all(m_st)
dev.off()
```

```{r peak_throughput_table}
peak_throughput_table <- function(m) {
  mg <- m %>% dplyr::group_by(series, pe, attempt, aligner, machine) %>%
    dplyr::summarise(
        threads_div_max_threads=totthreads[which(threads_div_max == max(threads_div_max))[1]],
        threads_div_max=max(threads_div_max),
        tot_secs_40x_pe_best=min(tot_secs_40x_pe),
        tot_secs_40x_unp_best=min(tot_secs_40x_unp),
        time_for_40x=if(pe[1] == 'pe') { tot_secs_40x_pe_best } else { tot_secs_40x_unp_best })
  tabular((Heading() * aligner * Heading() * series) ~
          (Justify(c) * Heading() * identity * Heading() * machine * Heading() * pe * Justify(l) *
                  (Heading('Th') * threads_div_max_threads +
                          Heading('Krd/s') * Format(sprintf("%.2f")) * I(threads_div_max/1000) +
                          Heading('40x mins') * Format(sprintf("%.2f")) * I(time_for_40x/60) )), data=mg)
}
```

```{r thread16_throughput_table}
threadno_throughput_table <- function(m, no_thread) {
  mg <- m %>% dplyr::group_by(series, pe, attempt, aligner, machine) %>%
    filter(totthreads == 16 & series == 'parsing-batch')
  tabular((Heading() * aligner) ~
          (Justify(c) * Heading() * identity * Heading() * machine * Heading() * pe * Justify(l) *
                  (Heading('Krd/s') * Format(sprintf("%.2f")) * I(threads_div_max/1000) )), data=mg)
}
```

```{r throughput_table_prep1}
m_st$machine <- 'KNL (272 threads)'
m_sk$machine <- 'Skylake (96 threads)'
m_bm$machine <- 'Broadwell (112 threads)'
m <- rbind(m_st, m_sk, m_bm)

short = c(
    'baseline-old',
    'baseline-tbbspin',
    'baseline-tbbstd',
    'baseline-tbbq',
    'parsing-clean',
    'parsing-batch',
    'final-block',
    'final-block-multi2',
    'final-block-multi4',
    'final-block-multi8',
    'final-block-multi16',
    'final-mp16',
    'bwa')
long = c(
    'O-parsing, TinyThread++ spin',
    'O-parsing, TBB spin',
    'O-parsing, TBB standard',
    'O-parsing, TBB queueing',
    'D-parsing',
    'B-parsing',
    'L-parsing',
    'L-parsing, 2 outputs',
    'L-parsing, 4 outputs',
    'L-parsing, 8 outputs',
    'L-parsing, 16 outputs',
    'MP baseline',
    'BWA-MEM')

al_short <- c('bt', 'bt2', 'ht', 'bwa')
al_long <- c('Bowtie', 'Bowtie 2', 'HISAT', 'BWA-MEM')

machines_order <- c('Skylake (96 threads)', 'Broadwell (112 threads)', 'KNL (272 threads)')

# Standardize BWA results
m <- m[!is.na(m$series),]
for(i in 1:length(al_short)) {
  slc <- m[m$series == 'bwa',]
  slc$aligner <- al_short[i]
  m <- rbind(m, slc)
}
m <- m[m$aligner != 'bwa',]
```

```{r throughput_table_prep2}
# Give aligners better names
m$aligner <- ifelse(m$aligner == 'bt', 'Bowtie',
                    ifelse(m$aligner == 'bt2', 'Bowtie 2',
                           ifelse(m$aligner == 'bwa', 'BWA-MEM', 'HISAT')))

# Factorize some columns
m$aligner <- factor(m$aligner)
m$pe <- ifelse(m$pe == 'pe', 'Paired', 'Unpaired')
m$pe <- factor(m$pe)
m$machine <- factor(m$machine)
```

```{r reorder_series}
# Reorder the series factor so that rows come out the order we want
reord_series <- rep(0, nrow(m))
for(i in 1:length(short)) {
  reord_series[m$series == short[i]] <- i
}
m$series <- reorder(m$series, reord_series)
```

```{r reorder_machine}
# Reorder the series factor so that rows come out the order we want
reord_machine <- rep(0, nrow(m))
for(i in 1:length(machines_order)) {
  reord_machine[m$machine == machines_order[i]] <- i
}
m$machine <- reorder(m$machine, reord_machine)
```

In LaTeXiT, add the following to the preamble:

```
\usepackage{graphics}
\usepackage{booktabs}
\usepackage[table]{xcolor}
\newcommand\Tstrut{\rule{0pt}{2.6ex}}         % = `top' strut
\newcommand\Bstrut{\rule[-0.9ex]{0pt}{0pt}}   % = `bottom' strut
```

For underlines under Broadwell / KNL:

```
\cmidrule(lr){3-6}\cmidrule(lr){7-10}\cmidrule(lr){11-14}
```

For underlines on line just below that

```
\cmidrule(lr){3-4}\cmidrule(lr){5-6}\cmidrule(lr){7-8}\cmidrule(lr){9-10}\cmidrule(lr){11-12}\cmidrule(lr){13-14}
```

```{r throughput_table_big}
m_all <- data.frame(m)
m_all <- m_all %>% filter(series %in% short)
m_all$aligner <- factor(m_all$aligner)
m_all$series <- factor(m_all$series)
m_all$series <- plyr::mapvalues(m_all$series, short, long)
fn <- 'peak_throughput.tex_snippet.tmp'
write("\\resizebox{\\columnwidth}{!}{%", file=fn)
capture.output(latex(peak_throughput_table(m_all)), file=fn, append=T)
write("}", file=fn, append=T)

system('grep -v NA peak_throughput.tex_snippet.tmp > peak_throughput.tex_snippet.tmp2')
system('python postprocess_peak_throughput_ex.py peak_throughput.tex_snippet.tmp2 > peak_throughput.tex_snippet')
```

```{r throughput_table_baseline}
m_base <- data.frame(m)
m_base <- m_base %>% filter(series %in% short)
m_base$aligner <- factor(m_base$aligner)
m_base$series <- factor(m_base$series)
m_base$series <- plyr::mapvalues(m_base$series,
                c(
                  'baseline-old',
                  'baseline-tbbspin',
                  'baseline-tbbstd',
                  'baseline-tbbq',
                  'final-mp16',
                  'bwa'),
                c(
                  'TinyThread++ spin',
                  'TBB spin',
                  'TBB standard',
                  'TBB queueing',
                  'MP baseline',
                  'BWA-MEM'))

fn <- 'peak_throughput_baseline.tex_snippet.tmp'
write("\\resizebox{\\columnwidth}{!}{%", file=fn)
capture.output(latex(peak_throughput_table(m_base)), file=fn, append=T)
write("}", file=fn, append=T)

system('python postprocess_peak_throughput.py peak_throughput_baseline.tex_snippet.tmp > peak_throughput_baseline.tex_snippet')
```

```{r throughput_table_parsing}
short <- c('baseline-tbbq',
           'parsing-clean',
           'parsing-batch',
           'final-mp16')
long <- c('O-parsing',
          'D-parsing',
          'B-parsing',
          'MP baseline')
m_parse <- data.frame(m)
m_parse <- m_parse %>% filter(series %in% short)
m_parse <- m_parse %>% filter(aligner != 'BWA-MEM')
m_parse$aligner <- factor(m_parse$aligner)
m_parse$series <- factor(m_parse$series)
m_parse$series <- plyr::mapvalues(m_parse$series, short, long)

fn <- 'peak_throughput_parsing.tex_snippet.tmp'
write("\\resizebox{\\columnwidth}{!}{%", file=fn)
capture.output(latex(peak_throughput_table(m_parse)), file=fn, append=T)
write("}", file=fn, append=T)

system('python postprocess_peak_throughput.py peak_throughput_parsing.tex_snippet.tmp > peak_throughput_parsing.tex_snippet')
```

```{r throughput_table_final}
short <- c('parsing-batch',
           'final-mp16',
           'final-block',
           'final-block-multi16')
long <- c('B-parsing',
          'MP baseline',
          'L-parsing, 1 output',
          'L-parsing, 16 outputs')
m_final <- data.frame(m)
m_final <- m_final %>% filter(series %in% short)
stopifnot(nrow(m_final) > 0)
m_final$aligner <- factor(m_final$aligner)
m_final$series <- factor(m_final$series)
stopifnot(sum(m_final$series == short) > 0)
m_final$series <- plyr::mapvalues(m_final$series, short, long)

fn <- 'peak_throughput_final.tex_snippet.tmp'
write("\\resizebox{\\columnwidth}{!}{%", file=fn)
capture.output(latex(peak_throughput_table(m_final)), file=fn, append=T)
write("}", file=fn, append=T)

system('python postprocess_peak_throughput.py peak_throughput_final.tex_snippet.tmp > peak_throughput_final.tex_snippet')
```

```{r throughput_table_multi}
peak_throughput_table_knl <- function(m) {
  mg <- m %>% dplyr::group_by(series, pe, attempt, aligner) %>%
    dplyr::summarise(threads_div_max_threads=totthreads[which(threads_div_max == max(threads_div_max))[1]],
              threads_div_max=max(threads_div_max))
  tabular((Heading() * aligner * Heading() * series) ~ (Justify(c) * Heading() * identity * Heading() * pe * Justify(l) * (Heading('Th') * threads_div_max_threads + Heading('Krd/s') * Format(sprintf("%.2f")) * I(threads_div_max/1000) )), data=mg)
}

short <- c('final-block',
           'final-block-multi2',
           'final-block-multi4',
           'final-block-multi8',
           'final-block-multi16',
           'final-mp16')
long <- c('L-parsing',
          'L-parsing, 2 outputs',
          'L-parsing, 4 outputs',
          'L-parsing, 8 outputs',
          'L-parsing, 16 outputs',
          'MP baseline')
m_multi <- data.frame(m)
m_multi <- m_multi %>% filter(series %in% short & aligner != 'BWA-MEM' & machine == 'KNL (272 threads)')
stopifnot(nrow(m_multi) > 0)
m_multi$aligner <- factor(m_multi$aligner)
m_multi$series <- factor(m_multi$series)
m_multi$series <- plyr::mapvalues(m_multi$series, short, long)

fn <- 'peak_throughput_multi.tex_snippet.tmp'
write("\\resizebox{\\columnwidth}{!}{%", file=fn)
capture.output(latex(peak_throughput_table_knl(m_multi)), file=fn, append=T)
write("}", file=fn, append=T)

system('python postprocess_peak_throughput.py peak_throughput_multi.tex_snippet.tmp > peak_throughput_multi.tex_snippet')
```

```{r mem_scaling}
bt2_u <- read.table('stampede_knl/stampede_knl_bt2_unp_scale.txt')
bt2_p <- read.table('stampede_knl/stampede_knl_bt2_pe_scale.txt')
bwa_u <- read.table('stampede_knl/stampede_knl_bwa_unp_scale.txt')
bwa_p <- read.table('stampede_knl/stampede_knl_bwa_pe_scale.txt')
bt2_u$pe = '100 nt unpaired  '
bwa_u$pe = '100 nt unpaired  '
bt2_p$pe = '100 x 100 nt paired  '
bwa_p$pe = '100 x 100 nt paired  '
bt2_u$aligner <- 'Bowtie 2'
bt2_p$aligner <- 'Bowtie 2'
bwa_u$aligner <- 'BWA-MEM'
bwa_p$aligner <- 'BWA-MEM'
ms <- rbind(bt2_u, bt2_p, bwa_u, bwa_p)
colnames(ms) <- c('nthreads', 'mem', 'pe', 'aligner')
```

```{r mem_scaling_plot}
mem_scaling_plot <- function() {
  ggplot(ms, aes(x=nthreads, y=mem/(1024 * 1024 * 1024), color=aligner, linetype=pe)) + geom_line(size=1) +
    scale_y_continuous(limits = c(0, 36)) +
    labs(x='# threads', y='Peak resident set size (GB)') +
    theme_bw() +
    theme(legend.title=element_blank(), legend.position="bottom")
}
mem_scaling_plot()

pdf(file='mem_scaling.pdf', onefile=F, width=6, height=4)
mem_scaling_plot()
dev.off()
```

```{r fstest}
ft <- read.csv('stampede_knl/fstest_nout_20180203.csv', header=T)
colnames(ft) <- c('Input', 'Output', 'nout', 'secs')
ftg <-ft %>%
    group_by(Input, Output, nout) %>%
    summarise(mean_secs=mean(secs))
short <- c('devnull',
           'ssd',
           'lustre1',
           'lustre16')
long <- c('Null',
          'SSD',
          'Lustre1',
          'Lustre16')
reord_in <- rep(0, nrow(ftg))
reord_out <- rep(0, nrow(ftg))
for(i in 1:length(short)) {
  reord_in[ftg$Input == short[i]] <- i
  reord_out[ftg$Output == short[i]] <- i
}
ftg$Output <- reorder(ftg$Output, reord_out)
ftg$Input <- reorder(ftg$Input, reord_in)
ftg$Output <- plyr::mapvalues(ftg$Output, short, long)
short <- short[2:4]
long <- long[2:4]
ftg$Input <- plyr::mapvalues(ftg$Input, short, long)

plot_fstest <- function(xlo = 1, ylo=0, yhi=200, ylab='Running time (secs, avg of 3 runs)') {
    ggplot(ftg, aes(x=nout, y=mean_secs, linetype=Input, color=Output)) +
        geom_line() +
        geom_point() +
        labs(x='# output files', y=ylab) +
        scale_y_continuous(limits = c(ylo, yhi)) +
        scale_x_continuous(limits = c(xlo, 16)) +
        theme_bw() #+
        #theme(legend .text=element_text(size=rel(0.55)))
}
unz <- plot_fstest()
zoom <- plot_fstest(8, 47.5, 67.5, '')
grid_arrange_shared_legend2(T, 1, 1, unz, zoom)

pdf(file='input_output_nout.pdf', onefile=F, width=7, height=4)
grid_arrange_shared_legend2(T, 1, 1, unz, zoom)
dev.off()
```

