#!/bin/bash

set -ex

if ! which git ; then
    module load git
fi

! which git && echo "No git in PATH" && exit 1

# ','.join(map(str, sorted(set([i for i in range(12, 112+1, 12)] + [i for i in range(8, 112+1, 8)] + [1]))))
THREAD_SERIES="1,8,12,16,24,32,36,40,48,56,60,64,72,80,84,88,96,104,108,112"

# Shorter reads for Bowtie; generated by the reads.py script
READLEN=50
READS_1="http://www.cs.jhu.edu/~langmea/resources/mix${READLEN}_1.fq.gz"
READS_2="http://www.cs.jhu.edu/~langmea/resources/mix${READLEN}_2.fq.gz"
READS_BLOCKED_1="http://www.cs.jhu.edu/~langmea/resources/mix${READLEN}_block_1.fq.gz"
READS_BLOCKED_2="http://www.cs.jhu.edu/~langmea/resources/mix${READLEN}_block_2.fq.gz"

REPO="https://github.com/BenLangmead/bowtie.git"

# Download reads to temp dir
for RD in $READS_1 $READS_2 $READS_BLOCKED_1 $READS_BLOCKED_2 ; do
    [ ! -f `basename ${RD}` ] && curl -O -J -L ${RD}
    gunzip `basename $RD`
done

READS_1=`basename $READS_1`
READS_1=`echo $READS_1 | sed 's/\.gz$//'`
READS_2=`basename $READS_2`
READS_2=`echo $READS_2 | sed 's/\.gz$//'`
READS_BLOCKED_1=`basename $READS_BLOCKED_1`
READS_BLOCKED_1=`echo $READS_BLOCKED_1 | sed 's/\.gz$//'`
READS_BLOCKED_2=`basename $READS_BLOCKED_2`
READS_BLOCKED_2=`echo $READS_BLOCKED_2 | sed 's/\.gz$//'`

# ftp://ftp.ccb.jhu.edu/pub/data/bowtie_indexes/GRCh38_no_alt.zip
if [ -z "${TS_INDEXES}" ] ; then
    echo "Set TS_INDEXES to directory containing indexes in bowtie, bowtie2 and hisat subdirectories" && exit 1
fi
REF=hg38

[ ! -f "${TS_INDEXES}/bowtie/${REF}.1.ebwt" ] && echo "Missing index: ${BT_INDEX}/${REF}" && exit 1

BASEDIR=$(dirname "$0")
CONFIG=${BASEDIR}/../bt1.tsv
[ ! -f "${CONFIG}" ] && echo "No such config file: \"%{CONFIG}\"" && exit 1

python ${BASEDIR}/../../master.py \
    --repo "${REPO}" \
    --reads-per-thread 450000 \
    --index "${TS_INDEXES}/bowtie/${REF}" \
    --m1 `basename ${READS_1}` --m2 `basename ${READS_2}` \
    --m1b `basename ${READS_BLOCKED_1}` --m2b `basename ${READS_BLOCKED_2}` \
    --input-block-bytes 12288 \
    --input-reads-per-block 75 \
    --sam-dev-null \
    --tempdir /tmp \
    --output-dir bt1 \
    --nthread-series "${THREAD_SERIES}" \
    --config "${CONFIG}"
